;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        add-review-comment
        backward-sexp
        beginning-of-buffer
        beginning-of-buffer-other-window
        bison-electric-greater-than
        bison-electric-pipe
        bison-indent-line
        c-electric-brace
        c-electric-colon
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-indent-line-or-region
        clipboard-kill-region
        clipboard-kill-ring-save
        clipboard-yank
        comment-region
        dabbrev-expand
        electric-graphviz-dot-semi
        electric-newline-and-maybe-indent
        end-of-buffer
        forward-sexp
        git-rebase-kill-line
        git-rebase-pick
        haskell-indentation-common-electric-command
        ido-switch-buffer
        indent-for-tab-command
        intero-repl-load
        kill-region
        markdown-outdent-or-delete
        next-error
        next-logical-line
        org-force-self-insert
        org-metaleft
        org-metaright
        org-self-insert-command
        overwrite-mode
        previous-logical-line
        resolve-trivial-conflicts
        sh-assignment
        wgrep-finish-edit
        ))

(setq mc/cmds-to-run-once
      '(
        buildsome-o
        c-electric-pound
        compile
        goto-line
        helm-M-x
        ido-find-file
        markdown-demote
        markdown-exdent-or-delete
        scroll-down-one
        scroll-right
        scroll-up-one
        undefined
        ))
